services:
  application:
    container_name: video_management_component_user_interfaces
    image: video_management_component_user_interfaces:0.0.1
    restart: always
    ports:
      - "4200:4200"

  nginx_http_hosting_server:
    container_name: nginx_http_server
    image: nginx_http_server
    ports:
      - "80:80"
    restart: always