http{
    include /etc/nginx/mime.types;
    sendfile      on;
    server {
        listen 80;

        root /usr/share/nginx/video_management_component_user_interfaces;
        index index.html index.htm;

        server_name _;
        location / {
            try_files $uri $uri/ /index.html =404;
        }
    }

}